### PR TITLE
Adding VID/PID for Mustang LT 40S

### PR DESCRIPTION
**Pull request by tim-littlefair**
I own this model, and I've discovered the PID/VID for it.  I realize this isn't a particularly major contribution, but I'm putting it out there as a means of opening communication, because I'm interested in reverse engineering in general, and in getting support for my own amp integrated in particular.

I've also done some Wireshark captures for the model, and will shortly invite you (https://github.com/offa) to have access to my (presently private) github repo where the captures are shared.  I'm more than happy for you to copy, publish and use these with or without attribution to myself.

I'm nervous about damaging my amp, so I'm planning to see whether the knowledge I get can be integrated into piorekf's upstream codebase rather than yours in the first instance.  My logic for trusting piorekf's codebase (slightly) more is that it is present in Debian and Ubuntu, probabily has a wider install base and I'd hope we'd have heard by now if anyone had mucked about with it and damaged their amp, but I'm still grateful for your update and completely open to experimenting with it at some later date.

Anyway, thanks again and best wishes with the project.

### CODE REVIEW

**Review by offa — APPROVED** [review]

**Comment by offa** [comment]
Thanks! :+1: 

I usually don't work on private projects as doing it as a community provides more knowledge.

> because I'm interested in reverse engineering in general, and in getting support for my own amp integrated in particular.

:+1: Newer Mustang devices seem to use a slightly different, but similar protocol. So figuring out the packet structures and stages is a good first step. Maybe you can get some help from the old protocol too.

> I'm nervous about damaging my amp,

Capturing packages or sending your own to the amp shouldn't damage it (_no guarantee though_). I have sent quite some garbage without damaging the device :smile:. The only part which could brick your device is the updater, but normal communications shouldn't do any harm.

> so I'm planning to see whether the knowledge I get can be integrated into piorekf's upstream codebase

As far as I know this wont work. The upstream project has gone for years now (thus this fork). But I can't speak for Debian / Ubuntu based development here.

**Comment by tim-littlefair** [comment]
Hi Offa,

Thanks for the very quick response.

Just to be clear, I didn't invite you as a participant on my private repo
because I expected you to work on it - you have your own project which
already embodies much more effort than mine and it would clearly be rude of
me to expect you to fall in behind my effort.  The reason I invited you was
so that you could look at the Wireshark captures I've done if you wanted
too.  If I get anything useful I'm more than happy to contribute it back to
your effort whether or not I can persuade Debian to look at opening the
older project up for update patches.

I am grateful for your codebase equally with piorekf's and I don't expect
anything for you.

Although...  the link to initialization.log on pioroekf's site has gone to
link rot and wayback doesn't seem to have a copy - if you have any captures
you can share for the amp versions which interoperate with your code or
piorekf's it might help me to work out how the protocol has changed and
turn that round to appropriate changes in either your or piorekf's code -
as I only have a modern amp I don't have a known-good working dump of the
initialization phase frome the original generation - and Technicalities.md
isn't that helpful until I have initialized and am looking at syncing sound
modes.

Anyway, thanks for the work to date, and best wishes.

Tim

**Comment by tim-littlefair** [comment]
Also, in relation to why my effort is private - if it became something I
had any pride in I would make it public.  But not until then.

**Comment by offa** [comment]
> Although...  the link to initialization.log on pioroekf's site has gone to
link rot and wayback doesn't seem to have a copy - if you have any captures
you can share for the amp versions which interoperate with your code or
piorekf's it might help me to work out how the protocol has changed and
turn that round to appropriate changes in either your or piorekf's code -
as I only have a modern amp I don't have a known-good working dump of the
initialization phase frome the original generation - and Technicalities.md
isn't that helpful until I have initialized and am looking at syncing sound
modes.

A good starting point is the initialization phase. Older Mustang devices use 64 byte packets with two fixed initialization packets. Packet and PacketSerializer implement those formats so maybe you can compare them with your captures.

> Also, in relation to why my effort is private - if it became something I
had any pride in I would make it public.  But not until then.

Don't be shy :-) Even if it's just some dump files it wont hurt being public (just make sure you don't publish any private data).

**Pull request merged**
